### ISSUE TITLE
PHP5-FPM crash when enbaled fast_shutdown

### ISSUE THREAD

**Issue by hu2008yinxiang** [zendtech/ZendOptimizerPlus#191]
PHP 5.5.9 (Ubuntu 14.04 iinstalled by apt-get install php5-fpm)
StackTrace

```
#0  0x00007f62a9341fc0 in ?? ()
No symbol table info available.
#1  0x00000000006f4813 in module_destructor ()
No symbol table info available.
#2  0x00000000006f9ac5 in ?? ()
No symbol table info available.
#3  0x00000000006fb2c8 in zend_hash_graceful_reverse_destroy ()
No symbol table info available.
#4  0x00000000006ed29e in zend_shutdown ()
No symbol table info available.
#5  0x000000000068eacb in php_module_shutdown ()
No symbol table info available.
#6  0x00000000007a7849 in ?? ()
No symbol table info available.
#7  0x00000000007a0aa6 in fpm_cleanups_run ()
No symbol table info available.
#8  0x00000000007a81b3 in ?? ()
No symbol table info available.
#9  0x00000000007a9190 in fpm_pctl_child_exited ()
No symbol table info available.
#10 0x00000000007a05f7 in fpm_children_bury ()
No symbol table info available.
#11 0x00000000007a4b26 in ?? ()
No symbol table info available.
#12 0x00000000007ae916 in ?? ()
No symbol table info available.
#13 0x00000000007a53f1 in fpm_event_loop ()
No symbol table info available.
#14 0x000000000079ff17 in fpm_run ()
No symbol table info available.
#15 0x0000000000463156 in main ()
```
Signal:11

BUT Application works fine with opcache.fast_shutdown=0

**Comment by laruence** [comment]
hmm, could you please check with the new version of PHP-5.5?

anyway, opcache is bundled with PHP since PHP-5.5, so maybe you should open issues in bugs.php.net instead . thanks
